#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { sanitizeSvg } from './sanitize-svg.mjs';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const assetsDir = path.join(projectRoot, 'assets');
const tsOutputPath = path.join(projectRoot, 'src', 'icons.ts');
const jsOutputPath = path.join(projectRoot, 'dist', 'icons.js');

const FONT_SOURCES = [
  { prefix: 'Merriweather_Regular', dir: 'Merriweather_Regular', preferHexNames: true },
  { prefix: 'Pirata_One', dir: 'Pirata_One', preferHexNames: false },
];

function ensureSvgRoot(body) {
  let svg = body.trim();
  if (!svg.startsWith('<svg')) {
    svg = `<svg xmlns="http://www.w3.org/2000/svg">${svg}</svg>`;
  } else if (!/xmlns=/.test(svg)) {
    svg = svg.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
  }
  return svg;
}

function escapeForTemplate(svg) {
  return svg.replace(/`/g, '\\`');
}

const DECIMAL_NAME_RE = /^\d+$/;
const HEX_NAME_RE = /^[0-9a-f]{4,}$/i;

async function collectGlyphs() {
  const glyphMap = new Map();
  const duplicateKeys = [];
  for (const source of FONT_SOURCES) {
    const fontDir = path.join(assetsDir, source.dir);
    const entries = await fs.readdir(fontDir);
    const svgFiles = entries.filter((name) => name.toLowerCase().endsWith('.svg'));
    svgFiles.sort((a, b) => {
      const aCode = Number(path.basename(a, '.svg'));
      const bCode = Number(path.basename(b, '.svg'));
      if (!Number.isNaN(aCode) && !Number.isNaN(bCode)) {
        return aCode - bCode;
      }
      return a.localeCompare(b);
    });

    for (const fileName of svgFiles) {
      const absPath = path.join(fontDir, fileName);
      const raw = await fs.readFile(absPath, 'utf8');
      const sanitized = sanitizeSvg(raw);
      const svg = ensureSvgRoot(sanitized);
      const basename = path.basename(fileName, '.svg');
      let keyName = fileName;

      const isDecimalCandidate = DECIMAL_NAME_RE.test(basename) && !/^0[0-9]+$/.test(basename);
      const isHexCandidate = HEX_NAME_RE.test(basename);

      if (isHexCandidate && (source.preferHexNames || !isDecimalCandidate)) {
        const codePoint = Number.parseInt(basename, 16);
        if (!Number.isNaN(codePoint)) {
          keyName = `${codePoint}.svg`;
        }
      } else if (isDecimalCandidate) {
        const decimalValue = Number.parseInt(basename, 10);
        if (!Number.isNaN(decimalValue)) {
          keyName = `${decimalValue}.svg`;
        }
      } else if (isHexCandidate) {
        const codePoint = Number.parseInt(basename, 16);
        if (!Number.isNaN(codePoint)) {
          keyName = `${codePoint}.svg`;
        }
      }

      const key = `${source.prefix}/${keyName}`;
      if (glyphMap.has(key)) {
        duplicateKeys.push(key);
        continue;
      }

      glyphMap.set(key, {
        key,
        literal: escapeForTemplate(svg),
      });
    }
  }

  if (duplicateKeys.length > 0) {
    const sample = duplicateKeys.slice(0, 10).join(', ');
    const suffix = duplicateKeys.length > 10 ? ', …' : '';
    console.warn(`[generate-icons] skipped ${duplicateKeys.length} duplicate glyphs: ${sample}${suffix}`);
  }

  return Array.from(glyphMap.values());
}

async function buildIconsFile() {
  const glyphs = await collectGlyphs();
  const header = [
    '// This file is auto-generated by scripts/generate-icons.mjs. Do not edit it manually.',
    "import { svg } from '@devvit/public-api';",
    '',
  ].join('\n');

  const body = glyphs
    .map((glyph) => `  "${glyph.key}": svg\`${glyph.literal}\`,` )
    .join('\n');

  const tsFooter = '\n} as const;\n';
  const jsFooter = '\n};\n';

  await fs.mkdir(path.dirname(tsOutputPath), { recursive: true });
  await fs.mkdir(path.dirname(jsOutputPath), { recursive: true });

  const tsContent = `${header}\nexport const Icons = {\n${body}${tsFooter}`;
  const jsContent = `${header}\nexport const Icons = {\n${body}${jsFooter}`;

  await fs.writeFile(tsOutputPath, tsContent);
  await fs.writeFile(jsOutputPath, jsContent);

  console.log(
    `[generate-icons] wrote ${glyphs.length} glyphs to ${path.relative(
      projectRoot,
      tsOutputPath
    )} and ${path.relative(projectRoot, jsOutputPath)}`
  );
}

buildIconsFile().catch((err) => {
  console.error('[generate-icons] failed', err);
  process.exitCode = 1;
});
